### ISSUE TITLE
CD/CI: Create github workflow

### ISSUE THREAD

**Issue by fixstars-sonali** [Sensing-Dev/WinUSB-installer-generator#2]
- [x] Create Develop workflow ed78574b5c18cb1f61375b25d6a9978342cc5a86
- [x] Create relaese workflow ed78574b5c18cb1f61375b25d6a9978342cc5a86
- [x] create test tag https://github.com/Sensing-Dev/WinUSB-installer-generator/actions/runs/7818164931
- [x] Verification

**Comment by Fixstars-momoko** [comment]
TODO: add basler vender_id

**Comment by Fixstars-momoko** [comment]
Worked on https://github.com/Sensing-Dev/WinUSB-installer-generator/pull/6
